# Generated by Django 6.0.7 on 2026-07-18 09:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('page_name', models.CharField(blank=True, max_length=200)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('time_spent', models.PositiveIntegerField(default=0, help_text='Seconds spent on page')),
                ('visited_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('is_bot', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Page Visit',
                'verbose_name_plural': 'Page Visits',
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['path', 'visited_at'], name='analytics_p_path_7ae18d_idx'), models.Index(fields=['visited_at'], name='analytics_p_visited_10fd53_idx')],
            },
        ),
    ]
