# Generated by Django 6.0.7 on 2026-07-10 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='bi-award', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Grant Categories',
            },
        ),
        migrations.CreateModel(
            name='VacancyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='bi-briefcase', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Vacancy Categories',
            },
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='opportunities/')),
                ('apply_url', models.URLField(blank=True, help_text='External application link')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grant_type', models.CharField(choices=[('scholarship', 'Scholarship'), ('research', 'Research Grant'), ('travel', 'Travel Grant'), ('startup', 'Startup Grant'), ('other', 'Other')], default='scholarship', max_length=20)),
                ('amount', models.PositiveIntegerField(blank=True, help_text='Grant amount in USD', null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('eligibility', models.TextField(blank=True, help_text='Who can apply?')),
                ('country', models.CharField(blank=True, help_text='Country of opportunity', max_length=100)),
                ('is_fully_funded', models.BooleanField(default=False)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.partner')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='opportunities.grantcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='opportunities/')),
                ('apply_url', models.URLField(blank=True, help_text='External application link')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('duration', models.CharField(choices=[('1_month', '1 Month'), ('2_months', '2 Months'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('1_year', '1 Year'), ('flexible', 'Flexible')], default='3_months', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('stipend', models.PositiveIntegerField(blank=True, null=True)),
                ('stipend_currency', models.CharField(default='USD', max_length=10)),
                ('field_of_study', models.CharField(blank=True, help_text='Relevant fields of study', max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.partner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='opportunities/')),
                ('apply_url', models.URLField(blank=True, help_text='External application link')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('remote', 'Remote'), ('contract', 'Contract')], default='full_time', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=10)),
                ('requirements', models.TextField(blank=True)),
                ('is_for_students', models.BooleanField(default=False, help_text='Suitable for current students')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.partner')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='opportunities.vacancycategory')),
            ],
            options={
                'verbose_name_plural': 'Vacancies',
                'ordering': ['-created_at'],
            },
        ),
    ]
